### ISSUE TITLE
How to enable Twig debug extension in services.yml

### ISSUE THREAD

**Issue by yeahsmaggy** [mheap/slim-demo#1]
Thanks for the excellent tutorial. I've been using it to refresh an old project I built in Slim. However, I can't figure out how to enable the Twig debug extension in services.yml https://github.com/mheap/slim-demo/blob/symfony-di/config/services.yml

it is inside:

`/vendor/twig/twig/lib/Twig/Extension/Debug.php
`
Before I just did 

```
 $loader = new Twig_Loader_Filesystem( array( '../src/views', '../src/views/admin', '../src/views/frontend' ) );
 $twig = new Twig_Environment( $loader, array(
     'cache' => './compilation_cache',
     'debug' => true
   ) );
 $twig->addExtension( new Twig_Extension_Debug() );

```

**Comment by yeahsmaggy** [comment]
Added the followed to enable twig dump function e.g. {{dump(foobar}}

```
  TwigExtensionDebug:
    class: \Twig_Extension_Debug
  View:
    class: \Slim\Views\Twig
    arguments: [["../src/views"], {"cache": "./compilation_cache", "debug": "true"} ]
    calls:
      - [addExtension, ['@TwigExtension']]
      - [addExtension, ['@TwigExtensionDebug']]
```
